title: Corina Acosta
author: Corina Acosta
markdown: redcarpet
port: 4000
pygments: true
permalink: /:categories/:year/:month/:day/:title 
exclude: ["README.md", "sass", ".sass-cache"]
production_url : http://www.iamcorinaacosta.com
baseurl: /
rss_path: /rss.xml
paginate: 5
excerpt_separator: "\n\n"
prose:
  rooturl: '_posts'
  siteurl: 'http://www.iamcorinaacosta.com'
  relativeLinks: 'http://www.iamcorinaacosta.com/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          type: "text"
      - name: "date"
        field:
          element:
          placeholder:: "2012-07-24 14:00:00 UTC"
      - name: "author"
        field:
          element: "hidden"
          value: "Corina Acosta"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Post Category"
          placeholder: "Create or choose"
          alterable: true
      - name: "comments"
        field:
          element: checkbox
          label: "Comments"
          value: "false"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true